### ISSUE TITLE
JS error caused by new line with Notes field

### ISSUE THREAD

**Issue by kerrig** [barrelstrength/craft-sprout-base-fields#2]
This was originally resolved by this pull request: https://github.com/barrelstrength/craft-sprout-base-fields/pull/1

But it appears to have been reintroduced in the last round of commits: https://github.com/barrelstrength/craft-sprout-base-fields/commit/169d2ca541e89e2d992ade9733a282ef1ce73358#diff-a3e08b7b070ebb7604a5bc16fbd0dcb4

Currently having this issue on v3.4

This is causing other plugins to not render fields properly.

**Comment by BenParizek** [comment]
@kerrig Thanks for reporting. I've pushed a bugfix release (v3.4.1) that fixes the issue.

**Comment by kerrig** [comment]
Great, thank you!
